DROP TABLE IF EXISTS data;

CREATE TABLE data (
  id SERIAL PRIMARY KEY,
  key TEXT,
  item_type TEXT,
  publication_year TEXT,
  Author TEXT,
  Title TEXT,
  publication_title TEXT,
  ISBN TEXT,
  ISSN TEXT,
  DOI TEXT,
  urls TEXT,
  Abstract_Note TEXT,
  Dates TEXT,
  date_added TEXT,
  data_modified TEXT,
  access_date TEXT,
  pages TEXT,
  num_pages TEXT,
  issues TEXT,
  volume TEXT,
  number_of_volumes TEXT,
  journal_abbreviation TEXT,
  short_title TEXT,
  series TEXT,
  series_number TEXT,
  series_text TEXT,
  series_title TEXT,
  publisher TEXT,
  place TEXT,
  language TEXT,
  rights TEXT,
  Type TEXT,
  archive TEXT,
  archive_location TEXT,
  library_catalog TEXT,
  call_number TEXT,
  extra TEXT,
  notes TEXT,
  file_attachments TEXT,
  link_attachments TEXT,
  manual_tags TEXT
);

COPY data(key,item_type,publication_year,Author,Title,publication_title,ISBN,ISSN,DOI,urls,Abstract_Note,
Dates,date_added,data_modified,access_date,pages,num_pages,issues,volume,number_of_volumes,journal_abbreviation,
short_title,series,series_number,series_text,series_title,publisher,place,language,rights,Type,archive,
archive_location,library_catalog,call_number,extra,notes,file_attachments,link_attachments,manual_tags) 
FROM '/Users/Zahid/Desktop/data.csv' DELIMITER ',' CSV HEADER;
